name: Macos Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: macos-latest
    env:
      packageName: "HelloAction-${GITHUB_REF:11}"

    steps:
      - uses: actions/checkout@v1
      - name: package 
        run: |
          zip -r "${{ env.packageName }}-${{ runner.os }}.zip" src LICENSE README.md -r
          ls -lha

      - name: Create Latest tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          file: "${{ env.packageName }}-${{ runner.os }}.zip"
          asset_name: "${{ env.packageName }}-${{ runner.os }}.zip"
          tag: latest
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }} 