name: Windows Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      packageName: "HelloAction-${GITHUB_REF:11}"

    steps:
      - uses: actions/checkout@v1
      - name: package 
        run: |
          echo ${GITHUB_REF:11}
          echo ${{ env.packageName }}-${{ runner.os }}.zip
          7z a -tzip ${{ env.packageName }}-${{ runner.os }}.zip src LICENSE README.md -r
          dir
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "HelloAction-*.zip"
          # artifacts: "${{ env.packageName }}-${{ runner.os }}.zip"
          bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}
         