name: Windows Releases

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: windows-latest
    env:
      packageName: "HelloAction-${GITHUB_REF:11}"

    steps:
      - uses: actions/checkout@v1
      - name: package 
        run: |
          echo ${GITHUB_REF:11}
          echo ${{ env.packageName }}-${{ runner.os }}.zip
          7z a -tzip ${{ env.packageName }}-${{ runner.os }}.zip src LICENSE README.md -r
          dir

      - name: Create Latest tag
        uses: EndBug/latest-tag@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          file: "${{ env.packageName }}-${{ runner.os }}.zip"
          asset_name: "${{ env.packageName }}-${{ runner.os }}.zip"
          tag: latest
          overwrite: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}